name: Metrics

on:
  schedule: [{cron: "0 0 * * 1"}] # weekly updates
  workflow_dispatch: # manual update
  push: # when workflow file changes
    paths:
      - .github/workflows/metrics.yml

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Base
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: America/Detroit
          base: [header, activity, community, repositories, metadata]
          base_indepth: yes
          repositories: 150
      - name: Languages
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.languages.indepth.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes # languages
          plugin_languages_indepth: yes
          commits_authoring: Kelly Sovacool, kelly-sovacool, kelly-sovacool@users.noreply.github.com
          plugin_languages_analysis_timeout: 15
          plugin_languages_details: bytes-size, percentage
          plugin_languages_threshold: 2%
      - name: Contributions
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.notable.indepth.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_notable: yes # notable contributions
          plugin_notable_indepth: yes
          plugin_notable_repositories: yes
